services:
  - type: web
    name: student-hostel-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 120
    envVars:
      - key: FRONTEND_URL
        value: https://student-hostels-frontend-3d23.vercel.app
      - key: PYTHON_VERSION
        value: 3.8.13
      - key: DATABASE_URL
        value: sqlite:///student_hostel.db
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_SSL
        value: "True"
      - key: MAIL_USERNAME
        fromSecret: mail-username
      - key: MAIL_PASSWORD
        fromSecret: mail-password