services:
  - type: web
    name: student-hostel-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student_hostel
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USERNAME
        fromSecret: mail-username
      - key: MAIL_PASSWORD
        fromSecret: mail-password

